stages:
  - install
  - build
  - test

cache:
  paths:
    - node_modules/

install-deps:
  stage: install
  image: node:20
  script:
    - yarn install --frozen-lockfile

build-app:
  stage: build
  image: node:20
  script:
    - yarn build
  only:
    - merge_requests
    - branches
  artifacts:
    paths:
      - dist/
    expire_in: 1h

test-app:
  stage: test
  image: node:20
  script:
    - yarn test:unit
  only:
    - merge_requests
    - branches