    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   "c:/www/vasya";
			try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }
    }
